# Numpy

- Most important concepts
    - fetching the players who have height greater than 170 -> players = [(63,169), (70,189), (86,180), (45,130)] (weight,height)<br>
array[:,1] > 170 this creates a boolean array marking true for all the values satifying the condition and false otherwise.<br>
array[array[:,1] > 170] fetches the values which are true in the previous step
    - Creating arrays -> zeroes, ones, arange(start, end not included, step), np.random.randint(start, end not included, size = 10), np.random.random([rows, columns])
    -np.reshape(rows,columns) -> to reshape the array
    - np.vstack((array1,array2)), np.hstack((array1,array2)), np.absolute(array), np.power(array,power), where, searchsorted, sort, shuffle, unique, insert, delete

## Converting a list to an array
- np.array(list)

In [1]:
import numpy as np

list_example = [12,45,23,78]

array = np.array(list_example)
array

array([12, 45, 23, 78])

## Checking the datatype using type function
- type(array)

In [2]:
type(array)

numpy.ndarray

## Mathematical operations can be applied on arrays
   addition of lists give concatenation while addition of arrays give addition

In [7]:
array*2.54

array([ 30.48, 114.3 ,  58.42, 198.12])

In [23]:
# addition operation

#list concatenates
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)

#array performs addition
#if shape of both the arrays is not same then broadcasting error occurs therefore shape should be same or should be of the format (1*4) (4*1) which will give output of (4*4)
# in the second scenario 1st element of array1 gets added to 1st element of array2, 2nd element of array1 gets added to 2nd element of array2 and so on
array1 = np.array(list1)
array2 = np.array(list2)
print(array1 + array2)
print(array1.shape)
print(array1.ndim)

# 2nd scenario
array3 = np.array([1,2,3,4])
array4 = np.array([[1], [2], [3], [4]])
print(array3 + array4)

[1, 2, 3, 4, 5, 6]
[5 7 9]
(3,)
1
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


## Shape, Dimension and Datatype

- shape 
    - array.shape
    - rows * columns
    - [4,5,6] -> 3*1
    - [(63,169), (70,189), (86,180), (45,130)] -> 4*2

- dimension
    - array.ndim
    - number of axes
    - [4,5,6] -> 1 axis/dimension only
    - [(63,169), (70,189), (86,180), (45,130)] -> 2 axes/dimensions therefore 2D array therefore 1D array
    - [[1,2,3,4]] -> 2D/2 dimensional because outer list is also there<br>
    - print(np.array([1,2,3,4]).shape) -> (4,1)<br>
      print(np.array([1,2,3,4]).ndim) -> 1D<br>

      print(np.array([[1,2,3,4]]).shape)(1,4)<br>
      print(np.array([[1,2,3,4]]).ndim)2D<br>
    - the number of dimensions = number of square brackets opening/closing = number of loops required to iterate
    - or iterate through 1 loop using nditer function<br>for i in np.nditer(array):<br>
    print(i)

- datatype
    - array.dtype


In [35]:
# tuple that contains weight and height of players - 
players = [(63,169), (70,189), (86,180), (45,130)]
print(players[2][1])
print(len(players))

array = np.array(players)
print(array)
print(array.shape) # output = (4,2) - 4 rows and 2 columns.

# dimension of the array
print(array.ndim) # output - 2

# datatype of elements in the array
print(array.dtype)

print(np.array([1,2,3,4]).shape)
print(np.array([1,2,3,4]).ndim)

print(np.array([[1,2,3,4]]).shape)
print(np.array([[1,2,3,4]]).ndim)
print()

#iterating over the array
# number of loops required = number of dimensions
array_it = np.array([[1,2,3,4]])
for i in array_it:
    for j in i:
        print(j,i)
print()

#nditer function
for i in np.nditer(array_it):
    print(i)

#converting the datatype of the elements to String while iterating
print()
for i in np.nditer(array_it, flags = ['buffered'], op_dtypes = ['S']):
    print(i)

180
4
[[ 63 169]
 [ 70 189]
 [ 86 180]
 [ 45 130]]
(4, 2)
2
int32
(4,)
1
(1, 4)
2

1 [1 2 3 4]
2 [1 2 3 4]
3 [1 2 3 4]
4 [1 2 3 4]

1
2
3
4

b'1'
b'2'
b'3'
b'4'


## Multiplication of 2D arrays
- first column gets multiplied with first column and second column gets multiplied with second column if you multiply manually
- for proper matrix multiplication either use np.matmul(array1, array2) or array1 @ array2

In [15]:
# multiplying the first column with 3 and second column with 2

multiplied_array = array * [3,2]
print(multiplied_array)
print()

multiplied_array1 = np.matmul(array, [3,2])
print(multiplied_array1)
print()

multiplied_array2 = array @ [3,2]
print(multiplied_array2)

[[189 338]
 [210 378]
 [258 360]
 [135 260]]

[527 588 618 395]

[527 588 618 395]


## Accessing elements of arrays

In [7]:
# accessing the first row
print(array[0])

# accessing the second element of the first row
print(array[0][1])

# accessing the first column
print(array[:,0])

[ 63 169]
169
[63 70 86 45]


In [8]:
# fetching the players who have height greater than 170 -> players = [(63,169), (70,189), (86,180), (45,130)] (weight,height)
new_array = array[:,1] > 170 # this creates a boolean array marking true for all the values satifying the condition and false otherwise.
print(new_array)

new_array1 = array[array[:,1] > 170] # fetches the values which are true in the previous step
print(new_array1)

print(new_array1.shape)

[False  True  True False]
[[ 70 189]
 [ 86 180]]
(2, 2)


In [9]:
skill = ['batsman', 'bowler', 'batsman','bowler']
skill_array = np.array(skill) # size of the skill_array and the 'array' array should be same because we will be applying operations on them together
print(skill_array)
# fetch the height of all players who are batsman
batsman_array = array[skill_array == 'batsman']
print(batsman_array)

['batsman' 'bowler' 'batsman' 'bowler']
[[ 63 169]
 [ 86 180]]


## help function

In [10]:
# use help function whenever you are stuck anywhere, it tells the use of the function you mention in it 
help(np.ones) # tells what does the np.ones function does

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

## Creating a 1D array

In [11]:
# creating a 1D array with all 1s 
arr = np.ones(5)
print(arr)

print(arr.dtype) # output - float, by default the array created is of float type so if you want the array to be of some other datatype 
                          # you have to mention it explicitly

arr_int = np.ones(6,dtype = int)
print(arr_int)

# creating a 2D array
arr_2d = np.ones((6,4))
print('2d array - ')
print(arr_2d)

[1. 1. 1. 1. 1.]
float64
[1 1 1 1 1 1]
2d array - 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# creating a 1D array with all 0s. Everything is same just the function is different.

arr = np.zeros(5)
print(arr)

arr_int = np.zeros(6,dtype = int)
print(arr_int)


[0. 0. 0. 0. 0.]
[0 0 0 0 0 0]


## Creating a list

In [13]:
# create a list from a range L to R-1
list(range(1,5)) # creates a list from 1 to 4

[1, 2, 3, 4]

## creating an array using arange function

In [14]:
# create an array from range 0 to n-1
array3 = np.arange(5)
print(array3)

# np.arange(start, end(not included), step size)
array4 = np.arange(4,10,2)
print(array4)

[0 1 2 3 4]
[4 6 8]


## Random Function

In [15]:
# random function 1D array
# create an array using integers in the range L to R(not included)
array1 = np.random.randint(5,size = 10) # creates an array using integers in the range 0 to 5(not included) of size = 10
print(array1)

# create an array using integers in the range L to R(not included)
array2 = np.random.randint(3,6,size = 10) # creates an array using integers from 3 to 6(not included) of size = 10
print(array2)

[1 0 3 3 4 4 3 3 3 2]
[4 3 3 3 3 5 4 5 4 5]


In [16]:
# random function 2D array
np.random.random([3,4]) # 3 is the number of rows and 4 is the number of columns

array([[0.08591892, 0.85808647, 0.65943059, 0.91313623],
       [0.43579853, 0.86974801, 0.35852016, 0.59842332],
       [0.50311744, 0.67102536, 0.78244387, 0.88897655]])

## Note - the shape and dimension of the arrays should be same to apply the operation


## Stacking Arrays

In [17]:
# Stacking arrays

#hstack()-horizontal stack
#vstack()-vertical stack
a = np.array([1,2,3])
b = np.array([2,3,4])
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [18]:
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
array5 = np.arange(12).reshape(3,4) # 3*4
array6 = np.arange(20).reshape(5,4) # 5*4

np.vstack((array5,array6))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## Power Function

In [20]:
# power function for exponential operation
np.power(array5,2) # power 2 of all the elements of array5

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

## Absolute Function

In [21]:
# converting a negetive array into positive using abs or absolute function
neg_array = np.array([-1,-4,3,0,-66])

print(abs(neg_array))
# or
print(np.absolute(neg_array))

[ 1  4  3  0 66]
[ 1  4  3  0 66]


## Where Function 
- used to search an element in the array

In [37]:
array = np.array([1,2,3,4,1,2,5])

# where function returns the indices wherever the mentioned value is present
index = np.where(array%2 == 0)
print(index)

(array([1, 3, 5], dtype=int64),)


## Seach Sorted Function

In [52]:
array = np.array([1,2,4,5,6])

# searchsorted function returns the index where the value mentioned will be inserted in the sorted array
index = np.searchsorted(array, 3)
print(index)

index1 = np.searchsorted(array, 7, side = "left")
print(index1)

2
5


## Sort Array

In [53]:
array = np.array([6,5,4,3,2,1])

sorted_arr = np.sort(array)
print(sorted_arr)

[1 2 3 4 5 6]


## Shuffle Function

In [58]:
array = np.array([6,5,4,3,2,1])

np.random.shuffle(array)
print(array)

[4 3 1 6 2 5]


## Unique Function

In [62]:
array = np.array([6,5,4,3,2,1,1,6,4])

array = np.unique(array)
print(array)

array = np.unique(array, return_index= True, return_counts = True)
print(array)

[1 2 3 4 5 6]
(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5], dtype=int64), array([1, 1, 1, 1, 1, 1], dtype=int64))


## Resize and Flatten and Ravel Function

In [72]:
array = np.array([6,5,4,3,2,1,1,6,4])

array = np.resize(array, (3,3))
print(array)

print(array.flatten())
print(np.ravel(array))

[[6 5 4]
 [3 2 1]
 [1 6 4]]
[6 5 4 3 2 1 1 6 4]
[6 5 4 3 2 1 1 6 4]


## Insert Function
- doesnt take float values

In [90]:
array = np.array([6,5,4,3,2,1,1,6,4])

# arr1 = np.insert(array, index, value)

arr1 = np.insert(array, 3,[1,2])
print(arr1)

arr2 = np.insert(array, 3,[1,2], axis = 0)
print(arr2)

[6 5 4 1 2 3 2 1 1 6 4]
[6 5 4 1 2 3 2 1 1 6 4]


## Delete Function

In [92]:
array = np.array([6,5,4,3,2,1,1,6,4])

# np.delete(array, index)
np.delete(array, 2)

array([6, 5, 3, 2, 1, 1, 6, 4])